### ISSUE TITLE
Move "Community Settings" info to main badge page

### ISSUE THREAD

**Issue by elaine-huynh** [lestrato/badgepack#21]
> Since the "Community Settings" / "About Community" blurbs are pretty short, maybe move that info into the main community page ("Manage Badges") as a header?

**Comment by lestrato** [comment]
I agree that they don't occupy a lot of space. However, I'm worried that the two components aren't similar enough to put them on the same page. Maybe we can manage to put them in a left-hand side panel or something like that. There could be a little redesign needed here.

**Comment by elaine-huynh** [comment]
Adding comment to reiterate what we've discussed about this topic:
* Leave this until after leaderboard stuff is implemented
* If the leaderboard is visible for a community, keep community info to its own tab and add the leaderboard to the bottom of it
* If the leaderboard is _not_ visible for a community, move the community info to the same page as badges for earners
* Moderators will always have "Community Settings" in its own tab, since it is distinct enough of a feature to keep separate.
    * Furthermore, even if the leaderboard is invisible to earners, it could still be visible for moderators.
