### ISSUE TITLE
User profiles and viewing badges

### ISSUE THREAD

**Issue by elaine-huynh** [lestrato/badgepack#6]
> As a moderator, I would like to see which badges a certain student has collected.

> I'd like an easy way of seeing which badges have been earned in my community.

> It would be nice to see how many/which badges my TAs have assigned. Also, can there be a separation in the "moderator" role so that TAs can only award (and not create) badges?

> Why can't I see a list of people who have this particular badge?

> As a user, I would _really_ like to be able to view the badges of a person in shared communities. I do find it enticing to be able to compare myself to other students, and it makes me feel less sad when I see that I'm not the only one with 0 / 2 earned badges. :(

With regards to the `About Community` page:

> I would likely never look at the "About Community" page unless it shows information about other users in the community. For example, seeing who has the most badges at the moment, or something like that.

**Comment by lestrato** [comment]
How are we planning to implement a table that shows a user and all badges he/she implemented. If the community has 10+ badges, wont the table be too large?
